### ISSUE TITLE
What is the annotator id? Which annotator id I should use?

### ISSUE THREAD

**Issue by Bennett-Yang** [alan-turing-institute/TCPD#12]
I noticed that annotation file is the map from annotator id to change points, but I do not get what "annotator id" is meaning. Which  one I should use?

**Comment by GjjvdBurg** [comment]
Hi @Bennett-Yang, thanks for your question. The annotator id is a unique id assigned to each of the human annotators. Typically you would use all the annotations for a time series simultaneously, using one or both of the metrics introduced in our paper. The [analysis/scripts/metrics.py](https://github.com/alan-turing-institute/TCPDBench/blob/master/analysis/scripts/metrics.py) file implements both the f-measure and the covering metric and both expect a dictionary with the annotations.

Hope this helps! Please let me know if you need further assistance with the code.

**Comment by Bennett-Yang** [comment]
Thank you very much! Now I know how to make use of TCPD. Your amazing job really helps me a lot! : )

**Comment by GjjvdBurg** [comment]
Glad to hear it @Bennett-Yang!
