### ISSUE TITLE
dataset json verification error

### ISSUE THREAD

**Issue by ashutosh1807** [alan-turing-institute/TCPD#3]
Running collect action for dataset: apple ... Traceback (most recent call last):
  File "build_tcpd.py", line 115, in <module>
    main()
  File "build_tcpd.py", line 110, in main
    func(name, script)
  File "build_tcpd.py", line 85, in collect_dataset
    return run_dataset_func(name, script, "collect")
  File "build_tcpd.py", line 81, in run_dataset_func
    func(output_dir=dir_path)
  File "./datasets/apple/get_apple.py", line 134, in collect
    write_json(csv_path, target_path=json_path)
  File "./datasets/apple/get_apple.py", line 65, in wrapper
    raise ValidationError(target)
tcpd.apple.ValidationError: ./datasets/apple/apple.json
make: *** [collect] Error 1
Trying to run make command. It gives this error. What possible reason?

**Comment by GjjvdBurg** [comment]
Hi @ashutosh1807, thank you for raising this issue, I'm sorry to hear you're running into problems. Could you email me the ``apple.json`` file that was created? It will help me check the error. It's possible that this is due to a rounding error or something similar.

**Comment by GjjvdBurg** [comment]
Hi @ashutosh1807, I've just added a Dockerfile to the repository. If you'd like to try to use this, it might solve the issue.

**Comment by ashutosh1807** [comment]
It works now. Thank you @GjjvdBurg

**Comment by GjjvdBurg** [comment]
Glad to hear it @ashutosh1807! Thanks again for reporting this, it helps to make the project better!

**Comment by AnandShegde** [comment]
Hi, I am running into the exact same problem again, In the apple.json file that is created, a double quote is missing.
![image](https://user-images.githubusercontent.com/79975787/196607221-0b2a3bbb-1b6e-4774-9d2c-4b46da5d1897.png)
You can find the json file [here](https://drive.google.com/file/d/1MHCw2H-yAZbH9S1H8mfvgweod7WRWQKB/view?usp=sharing)
