### ISSUE TITLE
Rank plots

### ISSUE THREAD

**Issue by ashutosh1807** [alan-turing-institute/TCPD#4]
How come the summary for average table (in case of univariate) and the rank plot be different?
amoc 0.702
binseg 0.706
pelt .689
These are the scores for default cover metric. Then why the rankplot shows AMOC after PELT?
<img width="1011" alt="Screenshot 1942-03-08 at 2 05 17 PM" src="https://user-images.githubusercontent.com/34888417/83239387-6e4e5000-a1b5-11ea-9795-605feb8bdfee.png">
<img width="905" alt="Screenshot 1942-03-08 at 2 05 30 PM" src="https://user-images.githubusercontent.com/34888417/83239418-76a68b00-a1b5-11ea-9220-27cb186aa7f5.png">

**Comment by ashutosh1807** [comment]
<img width="396" alt="Screenshot 1942-03-08 at 2 17 55 PM" src="https://user-images.githubusercontent.com/34888417/83240558-334d1c00-a1b7-11ea-8eb8-134f26b5d66b.png">
On trying to reproduce your results segneigh ouperfroms amoc in terms of cover as evident. How can you claim that the rank is same irrespective of metric then?

**Comment by GjjvdBurg** [comment]
Hi @ashutosh1807,

Thank you for your question. I believe there may be some confusion on what these tables and figures exactly measure. The table measures the _average_ performance of a method on a certain metric computed over the univariate time series. On the other hand, the rank plots measure _how frequently_ a method performs as the best/second best/third best, etc. We do that by looking at the full table of results (in the appendix) and assigning a rank to each method on each dataset (the best method gets rank 1, the second best gets rank 2, and if there are ties we assign average ranks). This approach is based on [this paper](http://www.jmlr.org/papers/volume7/demsar06a/demsar06a.pdf). The rank plots show the average of these rank values over the univariate datasets. Thus, it's important to recognize that the table and rank plots _measure different things_: the table shows the average value on the performance metric, whereas the plots show the average ranks of the methods. Now, what happens for the methods that you mention is that AMOC does better on average, but PELT is more frequently one of the best performing methods.

With regards to your second question, I'm somewhat confused where this figure comes from, is this from the paper or is this one you've generated yourself? If I generate the figure for the default experiment with the covering metric, I get the following (using the latest version of [TCPDBench](https://github.com/alan-turing-institute/TCPDBench)):

![Screenshot from 2020-05-29 15-26-03](https://user-images.githubusercontent.com/3286696/83270734-ca6aa180-a1c0-11ea-8854-47bf81d959d1.png)

In any case, the average ranks of these methods are very close together, so we should be careful with making strong statements about differences in their relative performance. What I believe you refer to is that in version 1 of the paper and the benchmark, the first few methods were _ordered_ the same way regardless of the metric. Note that in the [latest version](https://arxiv.org/pdf/2003.06222v2.pdf) of the paper the ordering is no longer exactly the same, so we do not make this statement.

I hope this answers your questions.
