### ISSUE TITLE
Fails to collect iceland_tourism, and subsequent datasets, due to it being an xlsx file

### ISSUE THREAD

**Issue by INASIC** [alan-turing-institute/TCPD#7]
When trying to build the file, using `python build_tcpd.py -v collect` I encounter the following error for 

```Running collect action for dataset: iceland_tourism ... Traceback (most recent call last):```
and the error message I get is:
```xlrd.biffh.XLRDError: Excel xlsx file; not supported```

This is because the package [xlrd has explicitly removed support for anything other than xls files](https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported).

**Comment by INASIC** [comment]
# Solution

I was able to get past this problem by running the code:
`pip install 'xlrd>=1.1.0>=1.3.0,<1.1.1' --force-reinstall`, to revert xlrd to an older version where it still supported xlsx files. 

After doing so running `python build_tcpd.py -v collect` works fine without errors.

**Comment by GjjvdBurg** [comment]
Hi @INASIC, thank you for reporting this issue! To hopefully be a bit future-proof I've replaced xlrd with openpyxl, which does support the xlsx files. This has now been merged so building the dataset should work without any problems.
